### ISSUE TITLE
Published link to book cover is 404

### ISSUE THREAD

**Issue by DaveParr** [wsvincent/djangoforprofessionals#248]
In my copy of the book v 4 from Gum Road a few months ago this line:

> How about an image? You can download the book cover for Django for Professionals at [this link](https://github.com/wsvincent/djangoforprofessionals/blob/main/dfp.png). Save it into the directory books/static/images as dfp.png.

links to a URL that is currently 404. Tiny bug really, just an FYI. I suspect somewhere along the lines the file type got updated to jpg but the url didn't.

Thanks for the book, really enjoying it so far.

**Comment by wsvincent** [comment]
Hi @DaveParr,

Thanks for pointing that out. As I'm sure you saw, the [correct link is here](https://github.com/wsvincent/djangoforprofessionals/blob/main/dfp.jpg). I'll update that for the next version hopefully coming out soon.

If you're interested, the error happened because I use color images (png) in the digital version but black/white in the print edition (jpg). And so to flip between the versions, I do a replace all and clearly made a mistake once.

Anyway, thank you for pointing it out!
