### ISSUE TITLE
App doesn't serve uploaded images in production

### ISSUE THREAD

**Issue by Constuelo** [wsvincent/djangoforprofessionals#31]
I don't have much information to give apart from the images 404

This is after you create a new book / upload an image.

Other static assets work as usual

Does anyone have any ideas? Or come across this, I'm pretty certain my code matches

**Comment by Constuelo** [comment]
This is after completing every chapter in the book

**Comment by wsvincent** [comment]
Hi @Constuelo this is an error that has been fixed in the updated version of the book. The issue is that WhiteNoise [won't serve media files in production](http://whitenoise.evans.io/en/stable/django.html#serving-media-files), so you need to use [django-storages](https://django-storages.readthedocs.io/en/latest/) to do that.

**Comment by Constuelo** [comment]
Thanks I solved the issue using AWS S3
