### ISSUE TITLE
psycopg2.errors.UndefinedTable: relation "users_customuser" does not exist

### ISSUE THREAD

**Issue by denism89** [wsvincent/djangoforprofessionals#53]
Have finished first book and started second one. Hagin a great time and really enjoying material but i reached the dead end and hence i am writing here. 

As I was following the book and coding along i came across the error right after i enter the username after createsuperuser command. 

PS C:\Users\... \books> docker-compose exec web python manage.py createsuperuser
Username: dm
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/db/backends/utils.py", line 86, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "users_customuser" does not exist
LINE 1: ...is_active", "users_customuser"."date_joined" FROM "users_cus...
The above exception was the direct cause of the following exception:
....

I tried to solve it myself and didnt go well. Then shut down docker and deleted the project folder and started form beginning. And then i came across the same problem. i then used the code provided here at github and same problem keeps occurring. 

Any suggestions/ideas how to explore this error further and where to find resolution?

**Comment by wsvincent** [comment]
Hi @denism89, The `users` database table is not created for some reason. Good that you tried shutting everything down and starting from scratch, which is always my first step :)

Have you run `migrate` on the database before trying `createsuperuser`? That's the issue here, the table for `users` isn't there, though I'm not completely sure why. 

Closing for now. Reopen if you're continuing to have issues.
