### ISSUE TITLE
A question relating to resolve()

### ISSUE THREAD

**Issue by hazartilirot** [wsvincent/djangoforprofessionals#65]
```
def test_homepage_url_resolves_homepageview(self):
    view = resolve('/')
    self.assertEqual(view.func.__name__, HomePageView.as_view().__name__)
```

I've just finished the 4th chapter and a question arose in my mind. Could any one explain step-by-step what happens when we pass in '/' as an argument to resolve()? I'm not a native speaker nor do I have experience in coding though in web terms "resolver" is a kind of an interpreter URLs to IP addresses. I've tried to print the view and here's what I got:
`ResolverMatch(func=pages.views.HomePageView, args=(), kwargs={}, url_name=home, app_names=[], namespaces=[], route=)`

I figured out what we do next in **self.assertEqual**, but it's obscure how we get HomePageView from '/".  Does it look for the path in pages.urls.py and then get the view of the path? It's like a reverse() method interpreting **name='home'** to the **path**. 

Thanks for any assistance.

**Comment by wsvincent** [comment]
Hi @hazartilirot,

I assume you've seen the [docs for resolve](https://docs.djangoproject.com/en/3.0/ref/urlresolvers/#resolve). 

`resolve` is used by Django itself to confirm that a view or function resolves to the a certain URL. So in this case, we create a variable `view` that resolves to the homepage `/`. Then on the next line, we assert that a view that resolves to `/` matches HomePageView.

It does feel a bit like a roundabout way to test that HomePageView actually results in the URL we want, but this is often has it's done.

**Comment by ushchent** [comment]
Hi, I've been stuck with this last test for a while too, I mean the `self.assertEqual(view.func.__name__, HomePageView.as_view().__name__)` line.

Please correct me if I'm wrong, but since we are using a class-based view, its `*.as_view().__name__` attribute will always be equal to "view", not the url name. Right? Since the HomePageView inherits from TemplateView which in turn inherits from View.

Just created another CBV AboutPageView(TemplateView) and looks like its `resolve("/about/").func.__name__` is "view", not "about" as I put in the urlpatterns. But if i make a function-base view "about_view", then its works fine and returns the proper view names:
```
     about = resolve('/about/')
     self.assertEqual(about.func.__name__, about_view.__name__)
```
Many thanks to Will for the excellent book series!
